[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://smartlearn-backend-143y.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
