services:
  - type: web
    name: smart-multimodal-learning-api
    plan: free
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_NAME
        value: smart_learning_platform
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
